---
version: '2.1'

services:
  zookeep1:
    image: confluentinc/cp-zookeeper:7.4.3
    hostname: zookeep1
    environment:
      ZOO_MY_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: yes
    volumes:
      - ./zk-multiple-kafka-multiple/zookeep1/data:/data
      - ./zk-multiple-kafka-multiple/zookeep1/datalog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:7.4.3
    hostname: kafka1
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeep1:2181
      KAFKA_ENABLE_KRAFT: no
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeep1:2181
    volumes:
      - ./zk-multiple-kafka-multiple/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zookeep1

  kafka2:
    image: confluentinc/cp-kafka:7.4.3
    hostname: kafka2
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeep1:2181
      KAFKA_ENABLE_KRAFT: no
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeep1:2181
    volumes:
      - ./zk-multiple-kafka-multiple/kafka2/data:/var/lib/kafka/data
    depends_on:
      - zookeep1

  kafka3:
    image: confluentinc/cp-kafka:7.4.3
    hostname: kafka3
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeep1:2181
      KAFKA_ENABLE_KRAFT: no
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeep1:2181
    volumes:
      - ./zk-multiple-kafka-multiple/kafka3/data:/var/lib/kafka/data
    depends_on:
      - zookeep1

  kafka-ui:
    image: provectuslabs/kafka-ui:master
    depends_on:
      - kafka1
      - zookeep1
    ports:
      - 18080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeep1:2181
